const FILTER_PHONE = 'FILTER_PHONE';
const CLEAR_FILTERS = 'CLEAR_FILTERS';
const ORDER_PHONES = 'ORDER_PHONES';
const SELECTED_ALL = 'all';
const CHANGE_PAGE = 'CHANGE_PAGE';

export default {
    FILTER_PHONE, CLEAR_FILTERS, ORDER_PHONES, SELECTED_ALL
};