const FILTER_PHONE = 'FILTER_PHONE';
const CLEAR_FILTERS = 'CLEAR_FILTERS';
const ORDER_PHONES = 'ORDER_PHONES';
const SELECTED_ALL = 'all';
const CHANGE_PAGE = 'CHANGE_PAGE';
const DISPLAY_ON_PAGE = 3333;
const MAX_PAGING_BUTTONS = 3;

export default {
    FILTER_PHONE, CLEAR_FILTERS, ORDER_PHONES, SELECTED_ALL, DISPLAY_ON_PAGE, MAX_PAGING_BUTTONS
};